@domain = 'http://localhost:3000'
@internet = 'https://crispy-garbanzo-4jq7jw69vj9w3gx5-3000.app.github.dev'

###

GET {{domain}}/

###

GET {{domain}}/eventos

###

GET {{domain}}/patrocinios

###

GET {{internet}}/generate-secret

###

POST {{internet}}/verify-content